[package]
name = "multivibe-core"
version = "0.1.0"
edition = "2021"
license = "CC-BY-NC-4.0"

[dependencies]
cpal = "0.15" # Cross-platform audio
tokio = { version = "1.30", features = ["sync", "rt"] }
